#pragma once
enum E_RSC_LOAD_TYPE
{
    LOAD_EMPTY = 0, LOAD_IMG_FILE, LOAD_SND_FILE, LOAD_END
};

enum E_PLAYER_STATUS
{
    PLAYER_IDLE = 0, PLAYER_RUN, PLAYER_ATTACK, PLAYER_DEAD, PLAYER_END
};

enum E_WEAPON_TYPE
{
    WEAPON_SWORD = 0, WEAPON_BOW, WEAPON_END
};