#pragma once
enum E_RSC_LOAD_TYPE
{
    LOAD_EMPTY = 0, LOAD_IMG_FILE, LOAD_SND_FILE, LOAD_END
};

enum E_STORE
{
    STORE = 0, ARMORY, STORE_END
};

enum E_ITEM_TYPE
{
    ITEM_EXPENDABLE = 0, ITEM_GEAR, ITEM_END
};

enum E_PLAYER_STATUS
{
    PLAYER_IDLE = 0, PLAYER_ATTACK, PLAYER_DEAD, PLAYER_END
};

enum E_WEAPON_TYPE
{
    WEAPON_SINGLESHOT = 0, WEAPON_MAGNUM, WEAPON_BUCKSHOT, WEAPON_BARRAGE, WEAPON_END
};

enum E_DD_ITEM_TYPE
{
    DD_ITEM_SCORE = 0, DD_ITEM_HEAL, DD_ITEM_END
};